<?php

namespace SR\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

	public function getPostComments($id)  // methode utilisée pour récupérer les commentaires des News mais aussi des Event
	{
		$qb = $this->createQueryBuilder('c')
				  ->orderBy('c.postDate', 'DESC')
				  ->where('c.news=:id')
				  ->setParameter('id', $id);

		$result = $qb->getQuery()->getResult();

		return $result;



	}



}
