<?php

namespace SR\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	public function myFindAll($page,$nbPerPage)
	{
		$querybuilder = $this->createQueryBuilder('e')
					->orderBy('e.eventStartDate','DESC');
		$query = $querybuilder->getQuery();
		$query->setFirstResult(($page-1) * $nbPerPage)    // On définit l'evenement à partir de laquelle commencer la liste
		->setMaxResults($nbPerPage);				      // Ainsi que le nombre d'evenement à afficher sur une page


	 // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    	return new Paginator($query, true);
	}	

	public function getEventHome($limit)
	{
		$qb = $this->createQueryBuilder('e')
					->orderBy('e.eventStartDate','DESC')
					->setMaxResults($limit);

		$query = $qb->getQuery();
		return $query->getResult();

	}
}
